import { type NextRequest } from "next/server";
import { z } from "zod";
import { requireProjectActor } from "@/lib/auth/require-project-actor";
import { getAdminFirestore } from "@/lib/firestore/admin";
import { getProjectStateRepository } from "@/lib/projects/project-state-admin";
import { mergeAdjacentReviewedScenes, renameReviewedScene, restoreExcludedSourceBlock, splitReviewedScene } from "@/lib/scripts/scene-review";
import { FirestoreSceneReviewStore } from "@/lib/scripts/scene-review-state";
export const dynamic = "force-dynamic"; export const runtime = "nodejs";
const bodySchema = z.discriminatedUnion("action", [
  z.object({ action: z.literal("rename"), editVersion: z.number().int().nonnegative(), sceneId: z.string().min(1), reviewedHeading: z.string().trim().min(1).max(500) }).strict(),
  z.object({ action: z.literal("split"), editVersion: z.number().int().nonnegative(), sceneId: z.string().min(1), sourceSpanIndex: z.number().int().positive() }).strict(),
  z.object({ action: z.literal("merge"), editVersion: z.number().int().nonnegative(), firstSceneId: z.string().min(1) }).strict(),
  z.object({ action: z.literal("restore"), editVersion: z.number().int().nonnegative(), sourceBlockId: z.string().min(1), reviewedHeading: z.string().trim().min(1).max(500), insertAfterSceneId: z.string().min(1).nullable() }).strict(),
]);
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ projectId: string; revisionId: string }> }) { const actor = await requireProjectActor(); if (actor instanceof Response) return actor; const { projectId, revisionId } = await params; if (!await getProjectStateRepository().getOwnedProject(actor.userId, projectId)) return Response.json({ error: "PROJECT_NOT_FOUND" }, { status: 404 }); const body = bodySchema.safeParse(await request.json().catch(() => null)); if (!body.success) return Response.json({ error: "SCENE_REVIEW_UPDATE_INVALID" }, { status: 400 }); const firestore = getAdminFirestore(process.env.GOOGLE_CLOUD_PROJECT!); const store = new FirestoreSceneReviewStore(firestore); const current = await store.get(projectId, revisionId); if (!current) return Response.json({ error: "SCENE_REVIEW_NOT_FOUND" }, { status: 404 }); if (current.status !== "draft") return Response.json({ error: "SCENE_REVIEW_NOT_DRAFT" }, { status: 409 }); try { const next = body.data.action === "rename" ? renameReviewedScene(current as never, body.data.sceneId, body.data.reviewedHeading, body.data.editVersion) : body.data.action === "split" ? splitReviewedScene(current as never, body.data.sceneId, body.data.sourceSpanIndex, body.data.editVersion) : body.data.action === "merge" ? mergeAdjacentReviewedScenes(current as never, body.data.firstSceneId, body.data.editVersion) : await restoreExcludedBlock(firestore, projectId, current as never, body.data.sourceBlockId, body.data.reviewedHeading, body.data.insertAfterSceneId, body.data.editVersion); return Response.json(await store.replace(projectId, next, body.data.editVersion)); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "SCENE_REVIEW_UPDATE_FAILED" }, { status: 409 }); } }

async function restoreExcludedBlock(firestore: ReturnType<typeof getAdminFirestore>, projectId: string, revision: Parameters<typeof restoreExcludedSourceBlock>[0], sourceBlockId: string, heading: string, insertAfterSceneId: string | null, editVersion: number) { const scriptRef = firestore.collection("projects").doc(projectId).collection("scripts").doc(revision.scriptVersionId); const source = await scriptRef.collection("sourceBlocks").doc(sourceBlockId.replaceAll("/", "_")).get(); if (!source.exists) throw new Error("SCENE_REVIEW_SOURCE_NOT_FOUND"); return restoreExcludedSourceBlock(revision, source.data() as { id: string; page: number | null; blockIndex: number; text: string }, heading, insertAfterSceneId, editVersion); }
