import type { Firestore } from "firebase-admin/firestore";
import type { ProjectJob } from "@/lib/jobs/schemas";
import { ProjectJobError, type DurableProjectJob } from "@/lib/jobs/project-job-state";
import { randomUUID } from "node:crypto";
export class FirestoreProjectJobRepository {
  constructor(private readonly firestore: Firestore) {}
  private ref(projectId: string, jobId: string) { return this.firestore.collection("projects").doc(projectId).collection("jobs").doc(jobId); }
  async enqueue(job: ProjectJob): Promise<DurableProjectJob> { const duplicate = await this.firestore.collection("projects").doc(job.projectId).collection("jobs").where("idempotencyKeyHash", "==", job.idempotencyKeyHash).limit(1).get(); if (!duplicate.empty) return duplicate.docs[0]!.data() as DurableProjectJob; const record = { ...job, leaseToken: null, leaseExpiresAt: null, attempt: 0 }; await this.ref(job.projectId, job.id).create(record); return record; }
  async claim(projectId: string, jobId: string, now = new Date(), leaseMs = 60_000): Promise<DurableProjectJob> { return this.firestore.runTransaction(async transaction => { const ref = this.ref(projectId, jobId); const snapshot = await transaction.get(ref); if (!snapshot.exists) throw new ProjectJobError("JOB_NOT_FOUND"); const job = snapshot.data() as DurableProjectJob; const expired = job.leaseExpiresAt !== null && new Date(job.leaseExpiresAt) <= now; if (job.status !== "queued" && !(job.status === "running" && expired)) throw new ProjectJobError("JOB_NOT_CLAIMABLE"); const claimed = { ...job, status: "running" as const, leaseToken: randomUUID(), leaseExpiresAt: new Date(now.getTime() + leaseMs).toISOString(), attempt: job.attempt + 1 }; transaction.set(ref, claimed); return claimed; }); }
  async succeed(projectId: string, jobId: string, token: string, now = new Date()): Promise<DurableProjectJob> { return this.firestore.runTransaction(async transaction => { const ref = this.ref(projectId, jobId); const snapshot = await transaction.get(ref); if (!snapshot.exists) throw new ProjectJobError("JOB_NOT_FOUND"); const job = snapshot.data() as DurableProjectJob; if (job.status !== "running" || job.leaseToken !== token || (job.leaseExpiresAt && new Date(job.leaseExpiresAt) < now)) throw new ProjectJobError("JOB_LEASE_INVALID"); const done = { ...job, status: "succeeded" as const, leaseToken: null, leaseExpiresAt: null, finishedAt: now.toISOString() }; transaction.set(ref, done); return done; }); }
  async retryOrFail(projectId: string, jobId: string, token: string, maxAttempts: number, now = new Date()): Promise<DurableProjectJob> { return this.firestore.runTransaction(async transaction => { const ref = this.ref(projectId, jobId); const snapshot = await transaction.get(ref); if (!snapshot.exists) throw new ProjectJobError("JOB_NOT_FOUND"); const job = snapshot.data() as DurableProjectJob; if (job.status !== "running" || job.leaseToken !== token) throw new ProjectJobError("JOB_LEASE_INVALID"); const next = job.attempt < maxAttempts ? { ...job, status: "queued" as const, leaseToken: null, leaseExpiresAt: null } : { ...job, status: "failed" as const, leaseToken: null, leaseExpiresAt: null, finishedAt: now.toISOString() }; transaction.set(ref, next); return next; }); }
  async get(projectId: string, jobId: string) { const snapshot = await this.ref(projectId, jobId).get(); return snapshot.exists ? snapshot.data() as DurableProjectJob : null; }
}
