import { randomUUID } from "node:crypto";
import type { ProjectJob } from "@/lib/jobs/schemas";

export type DurableProjectJob = ProjectJob & { leaseToken: string | null; leaseExpiresAt: string | null; attempt: number };
export class ProjectJobError extends Error { constructor(readonly code: "JOB_NOT_FOUND" | "JOB_LEASE_INVALID" | "JOB_NOT_CLAIMABLE") { super(code); } }
export class InMemoryProjectJobRepository {
  private readonly jobs = new Map<string, DurableProjectJob>();
  async enqueue(job: ProjectJob): Promise<DurableProjectJob> { const existing = [...this.jobs.values()].find(item => item.projectId === job.projectId && item.idempotencyKeyHash === job.idempotencyKeyHash); if (existing) return structuredClone(existing); const record = { ...job, leaseToken: null, leaseExpiresAt: null, attempt: 0 }; this.jobs.set(job.id, record); return structuredClone(record); }
  async claim(jobId: string, now = new Date(), leaseMs = 60_000): Promise<DurableProjectJob> { const job = this.jobs.get(jobId); if (!job) throw new ProjectJobError("JOB_NOT_FOUND"); const expired = job.leaseExpiresAt !== null && new Date(job.leaseExpiresAt) <= now; if (job.status !== "queued" && !(job.status === "running" && expired)) throw new ProjectJobError("JOB_NOT_CLAIMABLE"); const claimed = { ...job, status: "running" as const, leaseToken: randomUUID(), leaseExpiresAt: new Date(now.getTime() + leaseMs).toISOString(), attempt: job.attempt + 1 }; this.jobs.set(jobId, claimed); return structuredClone(claimed); }
  async succeed(jobId: string, leaseToken: string, now = new Date()): Promise<DurableProjectJob> { const job = this.jobs.get(jobId); if (!job) throw new ProjectJobError("JOB_NOT_FOUND"); if (job.status !== "running" || job.leaseToken !== leaseToken || (job.leaseExpiresAt && new Date(job.leaseExpiresAt) < now)) throw new ProjectJobError("JOB_LEASE_INVALID"); const completed = { ...job, status: "succeeded" as const, leaseToken: null, leaseExpiresAt: null, finishedAt: now.toISOString() }; this.jobs.set(jobId, completed); return structuredClone(completed); }
  async retryOrFail(jobId: string, leaseToken: string, maxAttempts: number, now = new Date()): Promise<DurableProjectJob> { const job = this.jobs.get(jobId); if (!job) throw new ProjectJobError("JOB_NOT_FOUND"); if (job.status !== "running" || job.leaseToken !== leaseToken) throw new ProjectJobError("JOB_LEASE_INVALID"); const next = job.attempt < maxAttempts ? { ...job, status: "queued" as const, leaseToken: null, leaseExpiresAt: null } : { ...job, status: "failed" as const, leaseToken: null, leaseExpiresAt: null, finishedAt: now.toISOString() }; this.jobs.set(jobId, next); return structuredClone(next); }
  async get(jobId: string) { const job = this.jobs.get(jobId); return job ? structuredClone(job) : null; }
}
